import { StyleSheet } from 'react-native';
export default styles = StyleSheet.create({
    container:{
        flex: 1, 
        backgroundColor:'#fff'
    },
    topContainer:{
        flex:1, 
        justifyContent:'center',
    },
    loginTextContainer:{
        alignItems:'center', 
        justifyContent:'center', 
        height:100
    },
    loginTitleText:{
        color:'tomato', 
        fontWeight:'bold', 
        fontSize:33
    },
    textInputContainer:{
        alignItems:'center', 
        justifyContent:'center', 
        height:80
    },
    inputText:{
        borderWidth:1,
        borderColor:'#E0E5E8',
        borderRadius:6,
        width:351,
        height:56,
        paddingHorizontal:15
    },
    loginButtonContainer:{
        alignItems:'center', 
        marginTop:40
    },
    loginButton:{
        backgroundColor:'tomato', 
        borderRadius:56, 
        width:279, 
        height:56, 
        alignItems:'center', 
        justifyContent:'center'
    },
    loginText:{
        color:'white', 
        fontSize:19, 
        fontWeight:'bold'
    }
  });